#import <Foundation/Foundation.h>
#import "CMBarcodeLookupResponse.h"
#import "CMApi.h"

/**
* barcodeapi
* Barcode APIs let you generate barcode images, and recognize values from images of barcodes.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMBarcodeLookupApi: NSObject <CMApi>

extern NSString* kCMBarcodeLookupApiErrorDomain;
extern NSInteger kCMBarcodeLookupApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Lookup EAN barcode value, return product data
/// Lookup an input EAN barcode and return key details about the product
///
/// @param value Barcode value
/// 
///  code:200 message:"OK"
///
/// @return CMBarcodeLookupResponse*
-(NSURLSessionTask*) barcodeLookupEanLookupWithValue: (NSString*) value
    completionHandler: (void (^)(CMBarcodeLookupResponse* output, NSError* error)) handler;



@end
