#import <Foundation/Foundation.h>
#import "CMBarcodeScanResult.h"
#import "CMApi.h"

/**
* barcodeapi
* Barcode APIs let you generate barcode images, and recognize values from images of barcodes.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMBarcodeScanApi: NSObject <CMApi>

extern NSString* kCMBarcodeScanApiErrorDomain;
extern NSInteger kCMBarcodeScanApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Scan and recognize an image of a barcode
/// Scan an image or photo of a barcode and return the result.  Supported barcode types include AZTEC, CODABAR, CODE_39, CODE_93, CODE_128, DATA_MATRIX, EAN_8, EAN_13, ITF, MAXICODE, PDF_417, QR_CODE, RSS_14, RSS_EXPANDED, UPC_A, UPC_E, All_1D, UPC_EAN_EXTENSION, MSI, PLESSEY, IMB
///
/// @param imageFile Image file to perform the operation on.  Common file formats such as PNG, JPEG are supported.
/// 
///  code:200 message:"OK"
///
/// @return CMBarcodeScanResult*
-(NSURLSessionTask*) barcodeScanImageWithImageFile: (NSURL*) imageFile
    completionHandler: (void (^)(CMBarcodeScanResult* output, NSError* error)) handler;



@end
