#import <Foundation/Foundation.h>
#import "CMApi.h"

/**
* barcodeapi
* Barcode APIs let you generate barcode images, and recognize values from images of barcodes.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMGenerateBarcodeApi: NSObject <CMApi>

extern NSString* kCMGenerateBarcodeApiErrorDomain;
extern NSInteger kCMGenerateBarcodeApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Generate a EAN-13 code barcode as PNG file
/// Validates and generate a EAN-13 barcode as a PNG file, a type of 1D barcode
///
/// @param value Barcode value to generate from
/// 
///  code:200 message:"OK"
///
/// @return NSData*
-(NSURLSessionTask*) generateBarcodeEAN13WithValue: (NSString*) value
    completionHandler: (void (^)(NSData* output, NSError* error)) handler;


/// Generate a EAN-8 code barcode as PNG file
/// Validates and generate a EAN-8 barcode as a PNG file, a type of 1D barcode
///
/// @param value Barcode value to generate from
/// 
///  code:200 message:"OK"
///
/// @return NSData*
-(NSURLSessionTask*) generateBarcodeEAN8WithValue: (NSString*) value
    completionHandler: (void (^)(NSData* output, NSError* error)) handler;


/// Generate a QR code barcode as PNG file
/// Generate a QR code barcode as a PNG file, a type of 2D barcode which can encode free-form text information
///
/// @param value QR code text to convert into the QR code barcode
/// 
///  code:200 message:"OK"
///
/// @return NSData*
-(NSURLSessionTask*) generateBarcodeQRCodeWithValue: (NSString*) value
    completionHandler: (void (^)(NSData* output, NSError* error)) handler;


/// Generate a UPC-A code barcode as PNG file
/// Validate and generate a UPC-A barcode as a PNG file, a type of 1D barcode
///
/// @param value UPC-A barcode value to generate from
/// 
///  code:200 message:"OK"
///
/// @return NSData*
-(NSURLSessionTask*) generateBarcodeUPCAWithValue: (NSString*) value
    completionHandler: (void (^)(NSData* output, NSError* error)) handler;


/// Generate a UPC-E code barcode as PNG file
/// Validates and generate a UPC-E barcode as a PNG file, a type of 1D barcode
///
/// @param value UPC-E barcode value to generate from
/// 
///  code:200 message:"OK"
///
/// @return NSData*
-(NSURLSessionTask*) generateBarcodeUPCEWithValue: (NSString*) value
    completionHandler: (void (^)(NSData* output, NSError* error)) handler;



@end
