#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* barcodeapi
* Barcode APIs let you generate barcode images, and recognize values from images of barcodes.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMProductMatch.h"
@protocol CMProductMatch;
@class CMProductMatch;



@protocol CMBarcodeLookupResponse
@end

@interface CMBarcodeLookupResponse : CMObject

/* True if operation was successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* Resulting product matches for the input barcode [optional]
 */
@property(nonatomic) NSArray<CMProductMatch>* matches;

@end
